const Map<String, String> appStringsVi = {
  'appName': 'Random Decision',
  'appTagline': 'Quay vòng quay — để số phận quyết định!',
  'splashLoading': 'Đang tải vòng quay...',
  'onboardingTitle1': 'Quay để chọn',
  'onboardingDesc1': 'Thêm lựa chọn và quay vòng quay đẹp mắt để chọn ngẫu nhiên trong vài giây.',
  'onboardingTitle2': 'Quản lý lựa chọn',
  'onboardingDesc2': 'Tạo danh sách đồ ăn, game, team hoặc bất cứ gì. Sắp xếp và sửa bất cứ lúc nào.',
  'onboardingTitle3': 'Kiếm sao & tùy chỉnh',
  'onboardingDesc3': 'Nhận sao mỗi ngày, mua gói qua Google Play, mở khóa skin vòng quay, theme và tính năng premium.',
  'getStarted': 'Bắt đầu',
  'skip': 'Bỏ qua',
  'next': 'Tiếp',
  'navWheel': 'Vòng quay',
  'navChoices': 'Lựa chọn',
  'navShop': 'Cửa hàng',
  'navSettings': 'Cài đặt',
  'wheelTitle': 'Random Decision',
  'wheelSubtitle': 'Nhấn quay — vòng quay chọn giúp bạn',
  'spinButton': 'QUAY!',
  'spinAgain': 'Quay lại',
  'spinning': 'Đang quay...',
  'resultLabel': 'Vòng quay chọn',
  'closeResult': 'Đóng',
  'needMoreChoices': 'Thêm ít nhất 2 lựa chọn trước',
  'choicesTitle': 'Lựa chọn của bạn',
  'choiceHint': 'Nhập lựa chọn mới...',
  'addChoice': 'Thêm',
  'choiceLimitReached': 'Đã đạt giới hạn — mở khóa không giới hạn trong Cửa hàng',
  'choiceLimitInfo': '{current}/{max} lựa chọn',
  'spinHistory': 'Lịch sử quay',
  'clearHistory': 'Xóa',
  'share': 'Chia sẻ',
  'shareResultPlain': 'Random Decision chọn: {result}',
  'shareResultBranded': 'Random Decision chọn: {result}\n\nTải app trên Google Play!',
  'adPlaceholder': 'Quảng cáo — Gỡ quảng cáo trong Cửa hàng',
  'removeAds': 'Gỡ QC',
  'save': 'Lưu',
  'cancel': 'Hủy',
  'shopTitle': 'Cửa hàng',
  'shopSubtitle': 'Kiếm sao hoặc mua thêm để mở khóa',
  'shopMenuAll': 'Tất cả',
  'shopMenuPremium': 'Premium',
  'shopMenuThemes': 'Theme',
  'shopMenuCards': 'Hình nền',
  'shopMenuSkins': 'Skin vòng quay',
  'shopMenuFeatures': 'Tính năng',
  'shopEmptyCategory': 'Không có mục trong danh mục này',
  'shopBrowse': 'Duyệt phần thưởng',
  'yourWallet': 'Ví sao của bạn',
  'coinsLabel': 'sao',
  'earnCoins': 'Kiếm sao miễn phí',
  'earnStepDaily': '• Đăng nhập hàng ngày: +10 sao',
  'earnStepSpin': 'Quay vòng quay',
  'earnStepSpinDesc': '• Mỗi lần quay: +3 sao (tối đa 10/ngày)',
  'earnStepAddChoice': 'Thêm lựa chọn',
  'earnStepAddChoiceDesc': '• Thêm mới: +2 sao (tối đa 5/ngày)',
  'earnStepShare': 'Chia sẻ kết quả',
  'earnStepShareDesc': '• Chia sẻ: +5 sao (tối đa 3/ngày)',
  'earnStepBuy': '• Mua gói sao qua Google Play',
  'claimDailyButton': 'Nhận +10 hôm nay',
  'dailyRewardDone': 'Đã nhận thưởng hôm nay',
  'buyCoins': 'Mua sao',
  'buyCoinsDesc': 'Mua gói sao để mở khóa nhanh hơn.',
  'yourCoins': 'Bạn có {count} sao',
  'coinPack': 'Gói {num}',
  'coinAmount': '{count} sao',
  'earnCoinsHint': 'Hoặc kiếm sao miễn phí ở phần ví phía trên.',
  'billingDisabled': 'Google Billing tắt — chỉ đổi bằng sao',
  'billingUnavailable': 'Google Play Billing không khả dụng',
  'productsNotFound': 'Không tìm thấy sản phẩm. Kiểm tra Play Console.',
  'processingPurchase': 'Đang xử lý giao dịch...',
  'openingBilling': 'Đang mở Google Play...',
  'configNetworkError': 'Lỗi mạng. Dùng cấu hình đã lưu.',
  'configTimeout': 'Hết thời gian chờ. Dùng cấu hình đã lưu.',
  'purchaseSuccess': 'Mua thành công!',
  'purchaseFailed': 'Mua thất bại',
  'insufficientCoins': 'Không đủ sao',
  'alreadyOwned': 'Đã sở hữu',
  'owned': 'Đã mua',
  'active': 'Đang dùng',
  'apply': 'Áp dụng',
  'applied': 'Đã áp dụng!',
  'resetDefault': 'Mặc định',
  'resetToDefault': 'Đã về mặc định',
  'shopRemoveAds': 'Gỡ quảng cáo',
  'shopRemoveAdsDesc': 'Ẩn banner quảng cáo vĩnh viễn.',
  'removeAdsIap': 'Mua qua Google Play',
  'removeAdsUnlocked': 'Đã gỡ quảng cáo!',
  'buyWithGooglePlay': 'Mua ngay',
  'shopThemeSunset': 'Theme hoàng hôn',
  'shopThemeSunsetDesc': 'Tông cam ấm áp.',
  'shopThemeMidnight': 'Theme đêm',
  'shopThemeMidnightDesc': 'Xanh đêm sâu lắng.',
  'shopThemeTropical': 'Theme nhiệt đới',
  'shopThemeTropicalDesc': 'Xanh tươi mát.',
  'shopThemeSakura': 'Theme sakura',
  'shopThemeSakuraDesc': 'Hồng hoa anh đào.',
  'shopBgSunrise': 'Bình minh',
  'shopBgSunriseDesc': 'Nền gradient cam ấm.',
  'shopBgOcean': 'Đại dương',
  'shopBgOceanDesc': 'Nền gradient sóng xanh.',
  'shopBgAurora': 'Cực quang',
  'shopBgAuroraDesc': 'Nền tím-xanh cực quang.',
  'shopBgGalaxy': 'Galaxy',
  'shopBgGalaxyDesc': 'Nền không gian sâu thẳm.',
  'shopSkinNeon': 'Vòng quay Neon',
  'shopSkinNeonDesc': 'Kim chỉ & viền phát sáng cyber.',
  'shopSkinClassic': 'Vòng quay Classic',
  'shopSkinClassicDesc': 'Phong cách casino vàng.',
  'shopSkinGlass': 'Vòng quay Glass',
  'shopSkinGlassDesc': 'Hiệu ứng kính mờ phát sáng.',
  'shopFeatUnlimitedChoices': 'Lựa chọn không giới hạn',
  'shopFeatUnlimitedChoicesDesc': 'Thêm tới 50 lựa chọn (miễn phí: 8).',
  'shopFeatWeighted': 'Quay có trọng số',
  'shopFeatWeightedDesc': 'Đặt trọng số cho từng lựa chọn.',
  'shopFeatSound': 'Âm thanh & rung',
  'shopFeatSoundDesc': 'Cảm nhận mỗi lần quay qua haptic.',
  'shopFeatHistory': 'Lịch sử quay',
  'shopFeatHistoryDesc': 'Xem kết quả quay gần đây.',
  'shopFeatExport': 'Xuất danh sách',
  'shopFeatExportDesc': 'Sao chép danh sách lựa chọn.',
  'shopFeatColors': 'Màu tùy chỉnh',
  'shopFeatColorsDesc': 'Mở thêm bảng màu vòng quay.',
  'shopFeatNoWatermark': 'Không watermark',
  'shopFeatNoWatermarkDesc': 'Chia sẻ kết quả không kèm thương hiệu app.',
  'coinsAdded': '+{amount} sao đã vào ví!',
  'dailyRewardClaimed': '+{amount} sao — thưởng hàng ngày!',
  'spinRewardEarned': '+{amount} sao — thưởng quay!',
  'addChoiceRewardEarned': '+{amount} sao — đã thêm lựa chọn!',
  'shareRewardEarned': '+{amount} sao — đã chia sẻ!',
  'coinRewardSub': 'Số dư ví: {balance} sao',
  'settingsTitle': 'Cài đặt',
  'language': 'Ngôn ngữ',
  'english': 'English',
  'vietnamese': 'Tiếng Việt',
  'darkMode': 'Chế độ tối',
  'privacyPolicy': 'Chính sách riêng tư',
  'activeTheme': 'Theme đang dùng',
  'activeBackground': 'Hình nền đang dùng',
  'activeSkin': 'Skin vòng quay đang dùng',
  'resetChoices': 'Đặt lại lựa chọn',
  'resetChoicesDesc': 'Khôi phục danh sách mẫu mặc định',
  'resetChoicesConfirm': 'Thay danh sách hiện tại bằng lựa chọn mặc định?',
  'appearance': 'Giao diện',
  'other': 'Khác',
  'exportSuccess': 'Đã sao chép danh sách',
  'openShop': 'Mở Cửa hàng',
  'openShopDesc': 'Skin, theme & mua sao',
  'copyright': '© 2026 Random Decision',
  'activeCustomization': 'Tùy chỉnh',
  'privacyPolicyTitle': 'Chính sách riêng tư',
  'privacyPolicyBody': 'Random Decision mặc định lưu danh sách lựa chọn, sao và vật phẩm cửa hàng ngay trên máy. Đăng nhập không bắt buộc.\n\nNếu tạo tài khoản, chúng tôi lưu email, biệt danh và lịch sử mua pack trên server để gắn giao dịch với bạn. Chúng tôi không tải danh sách vòng quay hay số sao lên.\n\nInternet còn dùng để lấy cấu hình IAP và xử lý mua hàng Google Play.\n\nGiao dịch do Google Play Billing xử lý. Chúng tôi không lưu thông tin thẻ.\n\nLiên hệ: support@randomdecision.app',
  'accountSection': 'Tài khoản',
  'accountGuestTitle': 'Chưa đăng nhập',
  'accountGuestDesc': 'Không bắt buộc — đăng nhập để lưu lịch sử mua pack.',
  'accountSignedIn': 'Đã đăng nhập',
  'accountShopHint': 'Đăng nhập để lưu lịch sử mua pack. Vẫn mua được khi chưa đăng nhập.',
  'authLoginTitle': 'Đăng nhập',
  'authRegisterTitle': 'Tạo tài khoản',
  'authLoginHeadline': 'Chào mừng trở lại',
  'authRegisterHeadline': 'Tạo tài khoản của bạn',
  'authOptionalHint': 'Đăng nhập không bắt buộc. App dùng bình thường không cần tài khoản — chỉ cần khi muốn lưu lịch sử mua.',
  'authEmail': 'Email',
  'authPassword': 'Mật khẩu',
  'authNickname': 'Biệt danh',
  'authNicknameHint': 'Hiển thị trên tài khoản',
  'authLoginAction': 'Đăng nhập',
  'authRegisterAction': 'Đăng ký',
  'authNeedAccount': 'Chưa có tài khoản? Đăng ký',
  'authHaveAccount': 'Đã có tài khoản? Đăng nhập',
  'authLogout': 'Đăng xuất',
  'authLogoutConfirm': 'Đăng xuất trên máy này? Danh sách và sao vẫn giữ trên điện thoại.',
  'authLogoutSuccess': 'Đã đăng xuất',
  'authLoginSuccess': 'Đã đăng nhập',
  'authRegisterSuccess': 'Đã tạo tài khoản',
  'authEmailRequired': 'Nhập email',
  'authEmailInvalid': 'Email không hợp lệ',
  'authPasswordShort': 'Mật khẩu tối thiểu 6 ký tự',
  'authEmailTaken': 'Email này đã được đăng ký',
  'authInvalidCredentials': 'Email hoặc mật khẩu không đúng',
  'authAccountLocked': 'Tài khoản đã bị khóa',
  'authValidationError': 'Kiểm tra lại email và mật khẩu',
  'authNetworkError': 'Lỗi mạng. Thử lại.',
  'authUnknownError': 'Có lỗi xảy ra. Thử lại.',
};
