const Map<String, String> appStringsEn = {
  'appName': 'Random Decision',
  'appTagline': 'Spin the wheel — let fate decide!',
  'splashLoading': 'Loading wheel...',
  'onboardingTitle1': 'Spin to decide',
  'onboardingDesc1': 'Add your options and spin a beautiful wheel to pick randomly in seconds.',
  'onboardingTitle2': 'Manage choices',
  'onboardingDesc2': 'Create lists for food, games, teams or anything. Reorder and edit anytime.',
  'onboardingTitle3': 'Earn stars & customize',
  'onboardingDesc3': 'Collect stars daily, buy packs via Google Play, unlock wheel skins, themes and premium features.',
  'getStarted': 'Get Started',
  'skip': 'Skip',
  'next': 'Next',
  'navWheel': 'Wheel',
  'navChoices': 'Choices',
  'navShop': 'Shop',
  'navSettings': 'Settings',
  'wheelTitle': 'Random Decision',
  'wheelSubtitle': 'Tap spin — the wheel picks for you',
  'spinButton': 'SPIN!',
  'spinAgain': 'Spin again',
  'spinning': 'Spinning...',
  'resultLabel': 'The wheel chose',
  'closeResult': 'Close',
  'needMoreChoices': 'Add at least 2 choices first',
  'choicesTitle': 'Your choices',
  'choiceHint': 'Enter a new option...',
  'addChoice': 'Add',
  'choiceLimitReached': 'Choice limit reached — unlock unlimited in Shop',
  'choiceLimitInfo': '{current}/{max} choices',
  'spinHistory': 'Recent spins',
  'clearHistory': 'Clear',
  'share': 'Share',
  'shareResultPlain': 'Random Decision picked: {result}',
  'shareResultBranded': 'Random Decision picked: {result}\n\nGet the app on Google Play!',
  'adPlaceholder': 'Ad space — Remove ads in Shop',
  'removeAds': 'Remove',
  'save': 'Save',
  'cancel': 'Cancel',
  'shopTitle': 'Shop',
  'shopSubtitle': 'Earn stars or buy more to unlock',
  'shopMenuAll': 'All',
  'shopMenuPremium': 'Premium',
  'shopMenuThemes': 'Themes',
  'shopMenuCards': 'Backgrounds',
  'shopMenuSkins': 'Wheel skins',
  'shopMenuFeatures': 'Features',
  'shopEmptyCategory': 'No items in this category',
  'shopBrowse': 'Browse rewards',
  'yourWallet': 'Your star wallet',
  'coinsLabel': 'stars',
  'earnCoins': 'Earn stars free',
  'earnStepDaily': '• Daily login: +10 stars',
  'earnStepSpin': 'Spin the wheel',
  'earnStepSpinDesc': '• Each spin: +3 stars (max 10/day)',
  'earnStepAddChoice': 'Add choices',
  'earnStepAddChoiceDesc': '• New choice: +2 stars (max 5/day)',
  'earnStepShare': 'Share result',
  'earnStepShareDesc': '• Share: +5 stars (max 3/day)',
  'earnStepBuy': '• Buy star packs via Google Play',
  'claimDailyButton': 'Claim daily +10',
  'dailyRewardDone': 'Daily reward claimed',
  'buyCoins': 'Buy stars',
  'buyCoinsDesc': 'Purchase star packs to unlock items faster.',
  'yourCoins': 'You have {count} stars',
  'coinPack': 'Pack {num}',
  'coinAmount': '{count} stars',
  'earnCoinsHint': 'Or earn stars for free in the wallet section above.',
  'billingDisabled': 'Google Billing disabled — redeem with stars only',
  'billingUnavailable': 'Google Play Billing is not available',
  'productsNotFound': 'Products not found. Check Play Console setup.',
  'processingPurchase': 'Processing purchase...',
  'openingBilling': 'Opening Google Play...',
  'configNetworkError': 'Network error. Using cached config.',
  'configTimeout': 'Request timed out. Using cached config.',
  'purchaseSuccess': 'Purchase successful!',
  'purchaseFailed': 'Purchase failed',
  'insufficientCoins': 'Not enough stars',
  'alreadyOwned': 'Already owned',
  'owned': 'Owned',
  'active': 'Active',
  'apply': 'Apply',
  'applied': 'Applied!',
  'resetDefault': 'Default',
  'resetToDefault': 'Reset to default',
  'shopRemoveAds': 'Remove ads',
  'shopRemoveAdsDesc': 'Hide banner ads permanently.',
  'removeAdsIap': 'Buy via Google Play',
  'removeAdsUnlocked': 'Ads removed!',
  'buyWithGooglePlay': 'Buy now',
  'shopThemeSunset': 'Sunset theme',
  'shopThemeSunsetDesc': 'Warm coral tones.',
  'shopThemeMidnight': 'Midnight theme',
  'shopThemeMidnightDesc': 'Deep blue night vibes.',
  'shopThemeTropical': 'Tropical theme',
  'shopThemeTropicalDesc': 'Fresh green mood.',
  'shopThemeSakura': 'Sakura theme',
  'shopThemeSakuraDesc': 'Soft pink blossom.',
  'shopBgSunrise': 'Sunrise glow',
  'shopBgSunriseDesc': 'Warm orange gradient backdrop.',
  'shopBgOcean': 'Ocean waves',
  'shopBgOceanDesc': 'Blue wave gradient backdrop.',
  'shopBgAurora': 'Aurora borealis',
  'shopBgAuroraDesc': 'Purple-green aurora backdrop.',
  'shopBgGalaxy': 'Galaxy night',
  'shopBgGalaxyDesc': 'Deep space gradient backdrop.',
  'shopSkinNeon': 'Neon wheel',
  'shopSkinNeonDesc': 'Cyber glow pointer & ring.',
  'shopSkinClassic': 'Classic wheel',
  'shopSkinClassicDesc': 'Golden casino style.',
  'shopSkinGlass': 'Glass wheel',
  'shopSkinGlassDesc': 'Frosted glass glow effect.',
  'shopFeatUnlimitedChoices': 'Unlimited choices',
  'shopFeatUnlimitedChoicesDesc': 'Add up to 50 options (free: 8).',
  'shopFeatWeighted': 'Weighted spin',
  'shopFeatWeightedDesc': 'Set weight per option for fair odds.',
  'shopFeatSound': 'Sound & haptics',
  'shopFeatSoundDesc': 'Feel every spin with haptic feedback.',
  'shopFeatHistory': 'Spin history',
  'shopFeatHistoryDesc': 'See your recent spin results.',
  'shopFeatExport': 'Export lists',
  'shopFeatExportDesc': 'Copy your choice list to clipboard.',
  'shopFeatColors': 'Custom colors',
  'shopFeatColorsDesc': 'Unlock extra wheel color palettes.',
  'shopFeatNoWatermark': 'No watermark',
  'shopFeatNoWatermarkDesc': 'Share results without app branding.',
  'coinsAdded': '+{amount} stars added to wallet!',
  'dailyRewardClaimed': '+{amount} stars — daily reward!',
  'spinRewardEarned': '+{amount} stars — spin reward!',
  'addChoiceRewardEarned': '+{amount} stars — choice added!',
  'shareRewardEarned': '+{amount} stars — result shared!',
  'coinRewardSub': 'Wallet balance: {balance} stars',
  'settingsTitle': 'Settings',
  'language': 'Language',
  'english': 'English',
  'vietnamese': 'Vietnamese',
  'darkMode': 'Dark mode',
  'privacyPolicy': 'Privacy policy',
  'activeTheme': 'Active theme',
  'activeBackground': 'Active background',
  'activeSkin': 'Active wheel skin',
  'resetChoices': 'Reset choices',
  'resetChoicesDesc': 'Restore default sample options',
  'resetChoicesConfirm': 'Replace your current list with default options?',
  'appearance': 'Appearance',
  'other': 'Other',
  'exportSuccess': 'Choices copied to clipboard',
  'openShop': 'Open Shop',
  'openShopDesc': 'Skins, themes & buy stars',
  'copyright': '© 2026 Random Decision',
  'activeCustomization': 'Customization',
  'privacyPolicyTitle': 'Privacy Policy',
  'privacyPolicyBody': 'Random Decision stores your choice lists locally on your device. We do not collect or upload your personal data.\n\nInternet is used only to fetch IAP configuration (R211.json) and process Google Play purchases.\n\nPurchases are handled by Google Play Billing. We do not store payment card information.\n\nContact: support@randomdecision.app',
};
